# Weighted sequence task configuration
graph:
  nodes_per_block: 10
  num_blocks: 7
  feature_dim: 16
  inter_block_connections: 2
  distance_threshold: 0.5

dataset:
  num_graphs: 1000

task:
  type: "weighted_sequence"
  special_node_selection: "one_per_block"
  oracle_connection_type: "sequential"
  nonlinearity: "tanh"