# Default configuration (original behavior)
graph:
  nodes_per_block: 10
  num_blocks: 5
  feature_dim: 16
  inter_block_connections: 2
  distance_threshold: 0.5

dataset:
  num_graphs: 1000

task:
  type: "default"
  special_node_selection: "endpoints_only"
  oracle_connection_type: "all_to_all"
  nonlinearity: "tanh"
