# Polynomial task configuration
graph:
  nodes_per_block: 10
  num_blocks: 7
  feature_dim: 16
  inter_block_connections: 1  # Reduced connections to make structure more important
  distance_threshold: 0.5

dataset:
  num_graphs: 1000

task:
  type: "polynomial"
  special_node_selection: "one_per_block"
  oracle_connection_type: "boosted_connections"
  boost_factor: 3
  polynomial_degree: 3
  nonlinearity: "tanh"